apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCrQJSucc7uCTDmwOhk9HZ1RkNB9mfiJ+SJZyIuJiVUnG/85ZC6jF0+O3s6rxQEd9+Hpl9rv9JisuXlnUURdb4up9KTMr7etZLcwGc29ZpvoBgTKPF3SqWjt1NgC5/z62rpNCrqmXcxx593BuYZK/VdjfIosoenvaXZk0GuhsGmSPjoFpWFEGa9cT0Vk4Y71+Ii3TDwIWiWDtkmcODb6+3F4YsGGCQi25voeKf9HIeUNecpVgCFkO77vLWIjQdnbPVc9eAsetpnEmAvCEjlRiiQfjEEITYvYbrRXPrGGjwj42JIgDNzbbPhg5gpmnCr7t7DI8eGgBnEzGJZ9iSJmPDV88o4qMg4fRyHqn5gmWevEOIoKkWyVjj6KStzW1739GUxnaiJiKBmFwPm5XQ3/hTg0EF/IJ38+ZWucc/MFf795KWmMygDVYWizaqF+zAHX1Ewx6yiWl4UdrLfHPhswIIstB9wAVW7QxHaSdNR1qYbbY3gCI5QjzT51Kepw0MKFGn7acuvumQPDNXvS+JnM4a0sTxpBF508FV2LJD3y6Y4zKFiPYzp2PtMIhQHGYO9M0JQyaDVKcg7jh5+Hj3t+VrAiTsKBS7fFIbxH+x0iOJslNHt0sC6cZFCNz2WMCiD74XNXCSEfIAgUp62AqPSB8GEgC2AEM1k1SXEn6YUM6Hnc+zCJcXh6OwokTgwE+//XyBQbZ+fHuHwwBY7H6FLLyPeL+48D2T03OSXbtOUrd0b8C+tCuWMWcap5g04Z41UilJwDE1iQJmahaoUwEREVFp08wg4qJCpQFQdNc619LDHNe2fwg24DswBQIkIqT/IhVTVCm7gAkj4c4HqnE8tRst8M3znjaR9M6NO65o4bHfPuBjWT/z5P92kHb7ceinzF+/QlIE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

