apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAZgA1JXHfIVyYr3LRZ6wPgIOtoMu3ldClO9e9Ra6f4d4i+t64ni1G1Pii2yBYqq9x3YOFG3Zd3nOWwokE0oL+Hwq74J3+kjYF0J/awnAPM5gAxDe8WWABKKunjGNoSggJ7Yde/Ru8lm1iCa0UDGfTsIBn9Aq6YXo+ZygAKNXMFMV5UmENfXtSie/+MdRh24EGuN08HCRgRMXnd7NJ/m8MAe9wwt0cK3eiN+6c6/6nfbFENMp5QLFDplWHCrQd1A/3/63D0zZHDZfQ0xbkzl8H7jAy0jZJ9oQyQlfCINgoWCrQjOXHFTvMW08boXuHKaXdj/euLnCpOeaTXrul0CsCbgRlP1gRE+dj2HycFxnfCo3SZ8T7PD5tZr8VRpWdS8mE5xROJ1wTKtlfCwmLSr36hmS/EtHfiaK52Sa2L21Vd80AZrmbktP2fqL3wC9J7BO0+Z4kNcGoIjd2VT8yk8JdvEtc1bMw5eB/X7+kAhaMmFEHp/Hucq46yQUoAeBmW5SQm6AfetOGM8w2UUCTsFeEJFgphWfbj7tdTb08Kwbk4xL+kNT4Le1i0caDwmMRkNccqRpwWUOxBzAu6zMGxY/hVxYgDONbIrI6taeofSI9vhqd0uTiAJ9Zo0BcI4NUmdrnd6NDepTlMcV0AO8bNRvTlalhjSztaknp0cVD4gy8fqZEdxroV+pt9nNPLoRY7pA+BvZ6BPtMJEzopGdALwC3LS4kT80YYXh7V+cS1MbVy8azUOoG8JkfAMmz0jeeDMMBqdhiau7c202TsJSh7hZ/iW+KQUlbC/IhNln01gLZIhHnaLT/5kWFh0YzXjfKtUdbtrD2qhJIeeonR7ng6jkCdgXE6sZuBd4hzzgR3TEcdJ5XuHWnFtMPF/qgcr1peGckAIF4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

