apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBtaJ7HXjAWXsmEWnYchOa23dRGUhW/XmY2qKBddUTJ8hCs+gPztRi55dJkrKa6CFBWlU8dth0KiVfjnsQkdYsxY1QQY/dRxJAg48+JUydHSv3Z6COLQpYFPIZVMMdLC1WVNE9pi+VZdldISMFp3WZFMZk7AP5tkdVWHtoLDxpNmWbH4hOgQM0N39ad+fu/NP5UGmagWNPY2l6leg3HQ017RWvjEC3GSr85bLRh+eNOyOLLznanNLKbgLqK8nJZR8cdSHvT0dkIgXfwnDZ2x7GRlfdWcWeeexvyew8jFQGWvfIutxQHFIxIQuotc6mvl9/zs+Xz2nbJD7tBHW6YQ7C0rL4Pv4chdrxA5nKhBGfiR6tPhVoQfoOeoaJasBsLG9taQq9Xkp0PQx/sLTH3GbSPHxnml9q+BeUivDzeaMftG5LgNkC1cZY5OuDV6QL2pN4eAuYxTKDJNO5JFdbX1+BF7JMpT7SVG4KYUm7vjvwNiIRMy045Iu0zakF2gNV24owOkR+avM7Ms5if6QZITHS/Tc1bTrv9fzQ+yGuHXMaATW5X5TKuBRMqnbFi0KI3fj8uoweZvBFpxxeEYxosNzB67YKnm5+6+M/RFOUOPDgABOi7VY6a7TcOR/53Qdlxw6U+wgBRbTtjRICPn1ryOGKLaA8iJ9hDmqanF/zeH15WhTVqZBBGVByGzk5USUw10xzNgmyZwP2lyHWQX9PtfTeez8bWitwNMbQ5Oqdc7pRBH1g/50K+ek7s9/OuypyOUfnkXui4b2gfh7/XxEuOaodiHmbxN5S6mAtTBKu8XIUWfucxr6NfkPCj4VFe07IqHQBdLgfOlGPiqv/S1KaQ4XH8V3ehwe+9O8LLStU6y6sK4R6WwWs4kcbdhgYjpsu5f4xhYQQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

