apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgALBdmhR7lD0rzxdB5hMs2jW3KQ+/SNPOqa5cjTyI3/lqsBpShieGDkTs6RS+PobS2DJw0m0hGOMjtkmBP/XDLm2HsVDoKNiJvuwJGI0D3Jd9IwB1u5imQTH0DxjOXdt8oMhcs/bBtOQSi8Not58Kj6B8ca9JFVg0YCrAmWRfwsxYMfCTEgA/lfJ30OD7cKh1VlQFrS59JxbLG6HoJBZoeNhYLD8KWjl1ERkyy0EagMOHo7RlmsOKlfWxbkAUl50kjxweWrtEIXjORawOeHrlGgtcD3XVDRSTuHrwhR36VGHxes/83uJzdSJTnT+QbzmRqLrH8/lDrGfCecZ0iXetFPjW8UwBfP3aaVNecfjjBXqe5BB30goA3jryPhjTMZmcJdwug4uJjxnBpFNHRQrvz+vbekBt8cSdRHaoQO4W2RVsjO/0Qyp8rgZFn0aiwbgcnvEH4AEPmKbZTLG16AhRmm4RP5yrpyfGB+aU4iohVmZBju2s/Uj0waNwofQD240ay28/C02T8IF4wThwys4FKG7u0K5ku/EIxVgn7bGp463JxBIc4cMOvMwJqOQVcGuZOy8HGXqMw0KHvDJtUSyGyFQnEomv/uWlMbehWfIXASraioBBhgfPSodKsdyl830fn/3yD9BsF9oM2wll0zsfl+nxCy0eYCfixVdRw1u2kmlhPHTHJ0zviNYcKPTm5TcZVKv8FeL4pK/rVs9XQnd7K6wQMH05OLXxbYQeVwzQjENL2gz4Atbsuv7W/cTmRrDUSv6Sbs8JPq5QZ5IsBf5K0DOrxwvRp0hw9tehlB2IVVWfQYWmusYahtykTWYnl9dsWrFR1HABWkraHPyL3tPK77MZ5/RdM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

