apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAC/aeNTTqquxpzoWWfoGWGu1z3FQR43/yDf3Fpy0WTtbJfjqShNQctIKkicqwHx0eUJK0+Dr7Fc2uNA0TNw8DTw1r9Gg4J8FH2cYK9nTKR/EylX2J5PCk8lv+jpmK1NS9ZCBV0UCBSfTzcb7ngoB5o1bvf6VLSelkloq5guQ7IRE++O1Erflzs05vX4i0z+qO0UFNYn77J9kvKdj9hq9RKtBHhvQ230teOPPx2w4EPkFmDt/S9/KQlj5DDekiyBqbHx/KCdv9fisV3Oc69m8WXwqSwB+t1XYFYQG5cOWWIIWEzBxqnOm8ML0jeofROza/NQKnoP1WNj9EZAd31dC7CPQozWhb6p8aNXZGPzfYyX1ThzgTaQoA7G9/SAG7UDqautvDYCYINjHp9ESc4ExorqL6mh9/8RKpB1gwRkkj1cG3C2hNnUj+rz4a1eMlON0re+Diksz33aelSplxRBEfM7IimCCaJe9E9GIWFv33yrp99vB+HPCvArICxsJtCkN69RG638KA0qUBC2mU1uS15GXGSOhPg1z0gxL+HpGk9VStuEphjswRRQmWaEyZVdn2YB4HVTRF3pfRIIedzDwasJQXPo5KrDMc8fbFYBUt4YZW92tGKA3ij7cCoPeuCoKU1Wk1NraIED1yMqpQvBUE6kD4jikT64b9HvC/+D2tf8ubF62IIiCzCMI4mOL/JVIzY+Xs4ShLBvTaQ5kfOU+0y3Fyn1NwWFHJoiPK5zjDTbjmnd3RtxCs3/G0iJG3jnWinOe/ISy5MqPHhwqG6H90csW9JjAD/d2kRwCqg1A2OppdTGSJk8hIhAVBm9DfGDeGdRnxBKY4aolKhR1Yg6p0+GEf4wxU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

