apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB9ZVTIR2swjZQ1PFSLqBOlTF9GCuqEW5pvwDu75YoUG54oNw486thqR8g2RtWXOPcghZ720Ohu9XPXxtAKKCoVoHXn5VorSyPadpf4ogrRdQypd44e+TiqNLPrMo7z0zQ/0psmT45t+YVL4PZ8PA7/0KcnF01YVw56nJOE1o3DcKvTGLe8i3/tXXhzffcCFTRDYo1ZAy9/9MotdPiYmu52mOlqxeqhOhaEdW8PS52KO1DCWE/WNqn4Y62DcvQOO+WrTY45uAF4WEYMG97gdZt1Ydj1lI2RLDx3tinbhf1M0r+7ulWnX2JfvLsm/wdnpTBb2SizOVX13LIGJ+UXHayJATp12Q652jVlBMjDCpl6mSi8l+yO8xtd2lqzP0NqprV9LvgCHIOkOa7sSkMVUqM66f2v0jmqdnNUlWP5AzaoAiTvOXkXCS1HJH3Huakxa43OPJkOgg7qw8Mxa3r0+5atUYZLQbj5AA+nmmnKrnYG718Tp92gn2qWK4+ATHnyde8Bf/sn6pibLhK2qrJskZIl8zDHz+MEgC7QEVvLSyMT73bzmXqwPzgmTLSfZOt5Go+yZt5r/lloA8/hl3fmiEUsBxisXX3hTw/Y0NZt2Mzlq1pOMpPFdkscW+GXmHC7mo8sVR22bGSo4jOWW2d7f6G19blUNcVbhWDFt0EdKHzSyQr8usL8aUbcbsssMVcL2pSJegkqVYncFm4as9ICpnzeK9YA9ukpWuw+cNyVAgrUvWaW0bWZbermzsn4cRCAUNeCdGjy2+yszrZZ6sA3CWxzFAN5+Q/PFJiVv6X8NuAw26A8ZdPFKE+zgO+eM8ggiPzp9c2wbVu1Am4OPzlsGVSJhzLlp697hn/nbkWMwjPo+mKqhqVdRWJv3fiQ3EQTTlzF6qY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

