apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCDBVSEFpfXfe3tECe87rytEHPKIKH3hV0hrqd5vy10+XaqfavRYjOB1YOOepq/G+lDMEj3/2tYqNHiKxISnmBqsRhxCzv3hIZdCYE0tOWax0vtoLmI1iFf8O0uzVd/3XuYgrO87ZQXTnxPEpF8cuFm7luYbY0lKUAgT0WJuNCh7CXLQtbt5gC6T46Y1j7oGjX9Kmnd9MWLWL2gPhu7TfX1gQrUR2UECZgox8Zc2ruf8/+W8gtRu+ebbfdHc2YJcJ9agGVkPeXux7UvGiUA6SMrHSTdQ1EDwYqSo0msRidH2wrba5/tDm8yUAebe7Tvw9aVoZ5TE/A2F1CnZc3AL7haii7F7XzYzA0QSp6cAlm039d3It/+3RAPO3QTywrh43TMXAIqxCvcomoiHAVqLnX1sSWYDkE/uEjyOJD2QsicQramZUjNI0Fh1k2AdZIKGK9Bh3x+AK8EiIaNh1H0oDd6HjPMi/M8LEQuiF778vydGmyddQlau8OI8umTQghihvWi3pkInXpEZupCty2KFWCq6yuSKteK+E1CHo3+EOV+IQ5Cq8VXEgLdz99JcHMm58VaPqz0g1sZWM79pRVZw62RWfIvrbSHy5gVeEYDqTowXQ9Kf8lnf3ybIuFL3UxQbMAmdUxEDklcAefG2zFzVnkJtg52xsfG0bEym1aPZAeVm5uy7DXuRtapxUt4flzt57gEklQUjZPDBcAv0bJrxRgU5gifM70psFh9LgmkFqO46u0kEa5HjpHjZ74kah9nAp1A7uoWSHanlH9xCSHMPSAsDmlEAzIkGya2hHO0ZwHtFpBViWpUeI4VQlMCH9WBvcw0YTLI2OADvqpV+lzD85nKkDj63ISebVw2FeHV1w+eqyHB7MVMe3qVNnibc9UYgSuQj7o=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

