apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCmhtosFBMT3lths0RzWbjdaLUiWCoFpH3npORLM7LwbTrVLt71KYV/i6IEox+SJnENK2XZXQYqCOmkjGPeBms43uxvSD1RelI3//scBf4WWIDIp3m6J9cA8syGYjAKZpQHxH+zVCoH7LKJLGWcRdtnhRW3x0uaW/BKZBYhGNVRkmnDSkEuf4k7l2GjdeI+1XiuBm8ZFq8QsPnnKMv+pzeQEy92WNFDUhNBjYAT7Vl/1Qsle5QXh7JR0KS4QE1AG0TWA/8IvPFUtEKxJpOb/05erqymeNMqE3/4fwerIYDLKZ8M3PnHtPfeOKmVllvUL13Wf+m5mdYopcHStEmVJLNAU6XWZcE5KmK69lYIlcupPdTBntz74ILxcRV6J2cG3+SE8VrJAkktxacVchIS7Xv8t4D4qo5C0O0+79Ra5YbEtq+gKsphD40qxoTLzPiWY9AS1I/uw+NQ5AZc3svHjhP+/yNu83CVqdU5lx2de3attmaAZkWWY2Qmh95z3E+jQ92nIYaiINxHO+RV/lmahFWY340Zi82n6mSU9axZs4uqjIy3g7WYvU+acPUNIyYGgPQXwKdy+ulRkHyudufVYgujDodtZ0J4LrLOAbOxcSrlSh9YIgv5xqHrrJmIHNMFL6HbR7Y4WktO6/fRy6Hk7x39yvxtEhJ7aYlR3piCj2VqGiZYNxFViVIfvI3wOOqM9iN80fph2IBcWrOE1rf3b/htoCid8dmY8fLUscbSV7OOOyKzxIyuF5DiZWa0ignbcBB2r4+0W4HuyownLV3NW5bxO7ToObM/HxwztLhwxmv7w7yNZJ0azSZhMvXodQy/baskH8AuNwNr5lY5WvR+gWfGM+TDfHE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

