apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDD951/Tucv5/kBrx+5H3Dci5PF6VZulrFohS4XotInWrcjuy2K8DH3StMk8Mhs0WtBKOAR5mBtRkwfRwBWxYdNOP7Otev9VOlSM1tstvFeFFzI+MiBIyOUEnvTri6/eP9oCMicvtcGldNGH6a6QQnwJjNRM6Sm78nIuB+e5yhN2zgC8tLsIiTw3Nsb2Rcs0FWo98XJmxw5+EtgKNmzdKExlVR8uPAHHixPCpFmDV/4VGr8ueLhMEbGdRlHdhRHNYL7sl9M10Uajg+sqsA2aA62U4tFLpOqoHyfOibVelOhUVYbfwoVM8SXd5+4dmORrgNCr9AqeT+kMX+zqbtZTCJ1tFm7fBh0TRwap8XZca3qnfb2gwtwv3X9384kEmkmeJPmTDTSyRoYvQibPh8FZpWaCD2TAN2xlPa7ZOJK/hsdMQ/JpXvOyMVmPQWcVV0piPbcwrutWgXyzkF6ZjRiM5s4odyAkoHsDHOQNYR3aMkUCyJISKGvyO8sEHgaAifgJ34+GXT/cy3hV9tVEXQjtNv63LMKrzlVIJkQ0ou6mszdtNgI0Bchi4Y3PkqRWKFP8GGtCScQcHRKoI82BowHFzgfnblxr1Cs8Kp+4hX55PlMiiHC44I78rnkcfuiVgJlHwlMusW0uIR/RiCiaQjTGytPKAcki44aYAKl/5kLszD7HUs2jwxTNP8bhLRDeiue7ZBV777KnN3/fyWLdt2WXzDaiYjtYqn7J7cRdP22WMNWPzozArJ2+Ftcze2MK4pem8wKZ5Zm/mt1sNW5xKOsCK7ssh4jy+R3fHeIlGslJknJujeJ1xoX78LtN0Mcvn0q3OWjBiRJBu9fWrVfSMo+q6qF5v+IKjVcrrEObmNCbX8LSviS/l8nZ/cFzd0152HtgkzYMlY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

