apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA+9ZIXxl2zno3NsImFIkF0r991F4VcPMkgoGAGapZooixFxr/eqH72Du7EX3w2Kc074bQMfL54GCxZyGsoKXpo0G/OFwoxFQX+S1YFyoD4QzWwDV4wvWLZk0g2K9FeOfR0/10z3qM0mFBEh9N+fxeHFxCC+j65630kYC4QBr+Q/xLRHTn1rJYMrImzDHwtzZBxLgOIPnJc8zn0b/G18IeBlb82UW6NkORQrEOTkUQrYHmhq6B04EC/JLXWiF9PmuKc/jMyuBHwRji14sMH0IybhgPcNmobhdukj4H2l/YLQmzdmu7O5vJqtGjLni5KAQx4ESrkZkzhP0e1CMvOpP9HLoyn8CQXU7xSqBC5A5xcHSmp7jSuXcRiTRoQJSbR+HUhz6rt3nLA5RWNgFEHhOlBI5dpyyxqyBIW1jcAFcmHX4RgLrC82WDNQxg4bA/XAsN7xvz9CMokjj2zn1l6rxX4/rk25tkSLSAE/SSjcd15EK0OfYw/J3hjQNFOnzrHS4Zovx0z5TnD05ptccZTtBo7tJ9i8exTAKsmUH4UN2YaQH7aVUazFz000T0RQFtAljM3QGNzrYqNl30ojPsUyq/tBNM1qAhsN6yx/vwBsP1xlkK5HwX9bam3BPDAMxlquhwjNdNsrTOyBDPICaPE1gdrMr0ZhDJcj2zriYNJF+d+QmudaUjadoHthJOC7lLerWWY+jOzxBuFcf1HfEXOO0GaL2+Id0BC7u5NLusupDdZgUmZ9wbh6/CFFfyyI1D6Fr91LRxN5ZjPh8c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

