apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCU8x2nmUBlWzpfzv1gnPsTRhee3XkMxkGw5Qs1JlM3XdYqCFwGIusazMcGqB0JDrubdVBrXYXimTfIWk+tNsFZNMuHmU6VtnRTIEVu9V+hpKfStMUJUZadWH8H4Y0ZW430ctLc35Q7/lll74vNsLP/u9M+oEX4wF2lMHtnnEA4enW4wpkUKX7e+a49Z1r7rHScl8utf8EQ4v0YCrZ7Em9hNpSAPHG0umC/V8R+BGnIDmCmAljaonHgNq3I2r9TXBs5mLZ6LM80BBi3QfscqS3n7I2t9yx+E7MvXjBpTMQ2VNJv7HKG0uMCBGu99MNdrPYt/iEjF8hknbtpafMUcn0G/5Q6/vyIDq6F6NgAk3wZZ4TMvFTo1HbwFIRYzRWqM5h8DDrwLUXH/D8kTwceI8RU/3FVcLOtYeQkmflPIurrk49hTNW0dqzUdaDSoo4XLmEaiNmWj8QKp06ZYh0yIY15F2bTFn7nKgsGjQzz2rkyJn6gtNm7VISXJLEnx1VjQUAbcltolZCt+XVlRM1fTgnqngZkBxTJTpasTzOMTv0g62iC3poMMSUFgsi5Sqm3rBaxn2nYqJBNPztpXRSfVgmFRU5mAtaJvA5KFkAR/1FS4xJhFOM3MBdKvtEbqfXLcMwpQRTCMuakVFZtTXnsPWFAj+57XnPipRvycjicJHo/i88cCAAsKOKzOnKdeHYlxikPbzSZX+W8Qb52H+02nETGUznW/qbvg/GhhW5RyFL+s/CcCM0QPxukNolf3aP8xY5tzf4Rlci11VTIeD8i6Dc3tJkKxuJ2IFm0agQmLfKpbyDZiI8WKbBmhaUMNE1Nwep9IvgviqXqWfNuLbrhfolxQJ+UsFYRh0BwBvuR64gH3xL7dC4wVTe2d00AXRpTICwolAM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

