apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCI9BQpVYt060wgxIPKgzQFJ8YYylXkhnQMx0GleivW9gVc8gygnQ5iLhqEYp7NE2A6yJvfsaQ1crav0YF6wnrxyJB2gHj1oB0B/qWzffGuPGgyiBS3yfa3jL17pF6csDmYQOv1kV2ANGDitup7Xrbu0b2w0ylsP6GLxsVzofLUJY5m2xbGEFs7tdgGth9ah7X/zORXhX7glgdKfBvgM/OtBQE3/vX0S4kF90JMr9T/VroSLUqQKkZv5jhj2mHBZVd6+g3dNnQgowY48tsz1j+JnfV4AgGOsE8oCDsgfYehpS0VGQlZ/Y7dx/7Jb2y9Jn7TnHkab5QBZYTB9AVx349xFWtvYoryILR58GDVQkat9GcVjrK4sawsXpMzZg38M0K18uCwgmD/nJaC7Z+I547VAXMs+7mt+HVmdgINqxt7h7v7dFn1x4L3eBZTIL+XtbryM6EWN/k2lZuUEZm48EjJox1flMgSkBCPuyotIyImdbOmBgWPL0vQu2PMPX7uQ3orEemzmPQjHrxrc8tNd1z/r8Uq4rM9pEK/gOm798SwbOsgDpWk9L+tBLgBykN3PmOVsK4nR6rcAGVpTnzJFlwkmcz5CvB//kmp7/JwS0TkzLgOhZrBR8Ma3YvEY/mmyRN6AMAeq3yeeb3MyPo1L8N9onGQou+rNBWWyrt5C9helN+cSBVS5i2fhhE873hRP+xCTNM4oJn8sueAQ/XwAgLOXVrBn7YxR5Fl+RRCoOB/Qt/lkfD7ylA31UQtTmrgnP5Mihs1psrUOLh8H/jRVDSY3MffTpqnKWPjcn8hp+V+BXOOElKX1nyGq/Lq7YOgc6HjZIzPpeKG49niujAHoLh8hG+AVaY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

