apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgByCFm2WmnzhhFdf57XCESIrd78xhv+VoS6BMzPuhNKfMDacQ0KuECM8N4ZEC3cJHWxNAS2kunQHjJPROGbd4CEBNoFvtBuZgy2/kwBLS3BfaDC7MErv4BkXnaAq7t5fShwGrkxVPCk7TJVyAUQFKso7oitHQTJmP2yo6MNuUchlwrLmQIfjLmJmDcTuKK4WpfaXN+ZFjV+ujmgYWMWMwd57UZR1aUjiVcloVOgCxIDWGTdLdAth375uZ9RVJaEIn8CPKefRuws603P3HZl/1pJJk3aCeDdhDrPHX+NFbzlqMR+kgkkHxccw4rSDUVnFFIgNMWbsTtopBC4HUsDoDPlnFR4l2308CypRrmtxJwzwfFDzqlcbryqhfowROuoFIWrll5q8aEUVbKFx6gPKP5W/V8NWwiOBUz7xhT8/9jf88Th6z01/tftCwGeNk7ATTBPzT5By1JMYuGlHALT88cyyi9eW9W69QJuwXIAZfW+dGiu0rk/R8FhLRhtvTG1pEC2ZAQjdXp7ObjrpiL89Tmw3sm0wLH3zPacO0MeHu/pGjYmS5EGIxwTUIQBZPZS/VDWm4xHpUS0mWWe2eOGHv9pM0FfkkSC4zLYzugA750kdOcFYqFYZ0iuuFmVxdfcqK6tUlWPBpoZ5q01ENo1QrZe3ItZENjAWgS1OZJ2I+ajjV57qYb6B26x2BOjIQoTtBeujPGvke0gNyIAN32GbOeiL34PWXdF1EgfqvjI5+wCcNbf4puzxkoSy3RGjsYV+zQjLvPa5XDI0SpGtDb5BKx3gWq+516dfJeRtoIrbhzUyP8w6HY+TCrygxtMpc0JOxSq+s6BHIDVzVltsNMOV9NyYQw7Kiw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

