apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBWHm/62qtK7AUv095TPJ2s8HboHORmb2lozc2jOCamAtZ+dGqmkCgKh5eENRnaOlo3XcujGITZTPcNvSHlyRftnY9pBQtj6VSr8djdeSeZS87SrYJFCJV48V4t26qQYwHcTefKA2C3jvm5XgMbiSQVsQ8DzLlvMtZFfLLLQQLb+JowfByjhEg3wCOe4HmRsHT3C2CYO2YOln9bIv4HGzG7rERRPGOsWVj2kjUUlX9opjkUdCQNGahrV2/wV7KzOSuCkfYkyYCQqAlJRaNjnWEShkg9+jgxrscZEaiH6s6GJYJFJDvBHBnUXDf66vMYpK6tkQLFxz3SuBSviLlw8ZHQ9AblBpkHAyZK/Vu701z66/SCEoFlA3xIQ1gIJejORnDSdkhZOgsIZ3PWy30XpNMkHNICdY/6qeNIXNBxmNEkZDwMMrhzPGN/Xo77azltgjuTA3WZs/757g/oLNL64Fbe3bmYKnHZQ9/gtRGt0V1WSHhWW7XbFTmDg/N5wqc02CEQkClx3wGPipZyHIzicWlHW2ennIyQX24th4yW1vDvhb/RmDM/NiKizhJcP2i5kzX36I+1wGSnhvqwZr1URSZDU2R73hachYZA0byQQfXn1MCsyDtLQVw1v79J3rV8YxfcKXnt2Q1UvTBG8zR2NMuTT7cWwB+Hz/SemLCdQi0owVfpsAWL8zKo46Xq9sB7JT3tM47JE3KorKNOtoUbNV3Cq5NMccqZ/Yo8u+04IrrFHzYl832vjwDO1ft9qcQESx9RiJSP3bmCLJrIXQDKZU69XQ3suUMN/A2OPkbqPGypF9wvii70JMQup+E/DXvZNIWm1RByipxLen82WiREZFwooD60DMc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

