apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCan152cwJjJfq1F/EDu9grO4QI5RUHjf3ik2zwkFsRzAHrBU9OjgCRLkPhJTOWCjWLGUFnfNkrEVpjjUlvxOJ/r0Kmfz+ZjxZUSE/Dko6lQdXee/7bSbiryNRgviNfemtuxP7CB9jlrem9H3JqfRlzNpJCnp1skN+EeBJJEnnJROHn/m4wCgHZJO8v6L38QbbGz8Fk7QX8uV/8ihplQn2Aux6i6ceonXQ3JE0FADIm3pqtqEElp4M5FYr85fMFpNkVSGBG42KeN3/Wm4EA+jvi6qHrUFbTo/0EqR4NzDlHo8XHxmgbtyImb/pmtCsj6ddPHjHpEo2d/Bs2dWKOQ0L629d1WFRMPbrUQen5q35dYeSR7GcY5O0LYubnvfiEQYL6VwKPFhnRc0LSiuvaSCSqIpJzlz/UaomzdX9980CK67Z2Bwq5OvUiSCznKFPXIyDfBO/xkvLyULIoCXTYW6fVlfjptmY6OMwwUdDt4iBgGZdb7wNKU5ZSNroY7mzSGXPbi0wqv5Nq4zxQvvjCa3M0U2YzUkED3CDpU6d1ljMLJ2hQ2k1790xvyEvBQ0bMGEK/oWQGihnmb+t/HpnBAwLl7DfeO5es7CR+Xq08CPp4zOt9Dz8xY55cwv6S5HWV0H1p2ksH/enjnSzKP+pAaiHuu6pxMlcPrq617vjiNO0Q9sdB0baHV/IwZV1aQiQTAmdam46Tw1ZW4R6WxWeah3Gd7K4o7+nL8jEu99ViXejgTQRlyLu8FIBOSy8nAKduob329bk4VuzvgLCyeFhpPfASzyqRX6+tiYDOjuMfMECtMstvw+gYkgBrMcl7Ct7nZK3cvUT8Na6lg+wbUaehwcDov2awS99zq2Fhu4PnvRWTiFpbUm8a+H7ejPywCpclLB3HEK0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

