apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAV7IkWbg0qMCgE1wsSH3nC+OPRA0FIElPNXKp0h+o4IAnFGW67QHjPxwmgVha2gThR9i9YlujCWj7CRq7i+Sm0Mrjbd1DBqdbcL7Lf6ZfRXX+3wHhHoNAx1508u1eMvRAQvhy5H1lXvlFIcqayYB0JUNrhPtpP4vWrRGuhQp+Gl8lZ2n6vUSfcnwioGOG81/TLbmStRc8yYf7pbnt5+WD+MRDtOaXxmx022517FteVKuxGCvHU4pBkhrm1E9LIoJhAoviNMokWkwBMvUMKjJUDdlCsL8MA01oS8M/zBKjgnvWXQuHz3efxQv0/92kDgW/v6JmqJKxEC0UJWCE65EHQwwetVZd8U5ZB8zHCydOfJUPYoMArAuFdakmjDVAZadmXPe8trnrRRxBQ5JpkBv6CabUNVHlQRSDc7w5hxzkqmTwf0FbCYIrfbowjc3rh5k9rEk4jWWijTRq+IhuPKs0UmA2R0mjqSnKy8vQBdM+oYEWVxM3z1jXaiEiGo2+6zhwNUUiRyM/y++020eArcluFsZHC8gNuiAwDeXIXNRJEZuuDhcO5BKLovXtE1tDlFoJm+YFAezuZTD8AsGxh6sGjgLeE3/zcK/HwBzycyrvtqSw89+ivSidgpycHkzmzizy0JXkGxV/qSQdJdqkpB0fbC96cIbB6ADHRi495g2Y80/ZB+gXIbznG0H18vd6Dvg7k8UpFxwU+KOTk0orhESupp3UIQWrs9BdFzKxGOl++XaNjq8bJg6EZk4UHSIFlpLDKQfHqfYRU5If6wb/ubYKyhe4gwLzH9ZP2wmuoI4DQBNwdAeB61C+X8X5DNHzOAgyMEiK2LFWXrUoiGFWdp5R3squJE6U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

