apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAD0srBPBlCOVah38spo+TSCtzmC5BH7bAzueAeYLv6cCGpHPwPdNWxhtMjDuqkTVjFtkluJFVQh9LTq2Dfz+d5lRV/GMzpglICgXpwqTJu0l/Y5sR/+jLtt+Dj2HZNO3BLYjYHM+9gNguklyWJWLqtvy8sYJAXP8meIIh4OBjNtN0ri8+pM00A73KFr4hEs82zvRJ2sGIUNltXtuJfhOt/KDnPV+MlMcSfb7gQ5DbqYGzF70sKtbtVQltngOa5VAxXtfnDaroA0LjbsfhppxmVbOCdRBBO/3J0cysmJhwAseksgKq0ClU+evPzxWtc20tDHEKrrurVp6qC8AP6LLMsX6jT9ARZsJN4C/ijXzrAHlbJLr9O7HVd6d62n6zB9s5+81y0qYgJIglAn1DV8MXQEcC7XaeJjuq2uCYz02lglAg/R0qkolqGWprQSRyEquH8VqiYK+4HN9YgZAnie+9wCZH2NzDEt1BRsO2BWf2xf0YO0QNE3I4ki9uzE0mrWrbBNIHhepDx8HPo1s85rT+2tLWu5/PnCjtwsXAvpimLTdlorwd52k4N9Su8+35b6OTNnFanFR8Rteb/0egHQU8NPCSXmAz4XSUHZqs+7iwySm4eV9o4U+tLcU3yQIwsc1RkfLO7GDaxAhLGgoIgKv6SqxJGdQEsncrnFKf18gfPhMhroNC6ZF/naodPqOo/qgsWo7ZMeUUbx4CQhMaEZabqRsuR51W9rMYnaY3aZpobp9u/gWPCHOA+xbVKZTPWWXLZrtFo6ZYhi7s8TOzYTknxBdBpq1nq+fF0Gw0R3HgYuFxiveZESF780187cSOgj6eMlqRKZBMEpy4uZJFmjzserSJ/rgk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

