apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCOsWqFAwx/QAqnkQeaPlcOD1C8Ny2ZE39kEyDtXfowcU54dtHtah+dc4j909LYxf675WxZNolukN38bvtGv8PR4LAxLfgpJlH8Y0KtFcajo2dypzYxhcuvYyekoJDL3DopaT9fa+qmdMq+RnYDZcQxdClVnHdrlo/GX2YhVcQncg/qE3chJCvew+fdOSS227l7Ry4C0JKpKlweyBJsyQCSigf37/7LHhCP9wTry/NF1h/N2NI+xoQ7CYmQYFcVVDUFSdOgpHtI2x3G4vi4vLdOY+UTlHiz+v46JoeDw+gdmxUxkNG9jjBy3IuP93heRgb9nFZjogHE7tn3RX7sSGUjhgl3TSNavuVIzWeGur/okuY8+0ww39gXzAjy3vxchAJdXCirAHPXx3PW9SQ/J1WWnQFYZZLuWzIdfLorQdddKTgx/vzfTALrjpEP17FqsKdUROzQqRQYukwio0n0ZYwvH5CN8ZHtI+e0u7CM+PzEg3zuwN1gM6gofWQXLHNHmyFx1h2u64hsyAVcOCDHpJSzj06Ye+UYMBCU25w7U4VfovpOLtDvIcgxoG9ghZk0gAHYWBXg8rwv9AFi1ufgW7vZHj0Bk8yjzWEWUrKi1ciwxznb5nAnSjlul9+as1398vGBIE9Eo0pGTFflCgr3mExzW9Sv5VvgqxAPBJKcRl5R3IivB9DZ0emeITZFAkTBDNdhkDv5jZNgOxiFKylHogfjmHUNClBC431L7xv8hUO5Vm6AEmA82EIz8KasEULAwpGa0yn8FfUu089ItJF+NRBgTqXAOj2BQHrywN1Gm1ya0UnjM5qk0ufkMNMm4k4ipiCD+8n1ZW8aDGYu8tPATMlZom402Udf21XUTLWm6leN/vsPVbt2kbo/6uDE1Aj6e96aPlM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

