apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAz3hTH/c03zv0N9HdRehiZMwPRq852oeSz1yW1u4vgX7OBILfIuFL2g+KNHqWoyY7LQILuZmbgw0oVDbslxESod+UmdX0bDs6VirVMYr3lMSHSHy0jpaMlokHm9I7H1x4mc6M0CCnYtPp1XdE2Afx+WTP9rBWra3OrLdvFkJZDuNOMLfD/XiIkPH/vlSm9+01kRXBOjM3VkrPA1WFCCamv12gj6sgwceG/sVI+1dqEjGUF3fz7lODb8FWYF/UopdomsKrGuSSQzn4JFO5omwcoGnw/rTZ+OCDYVRP7RqWpa9lD83XMPeacyPpr+RPEYUsfxkAhFGMGH3RnEW+wXRs2Uu0RvMrOgOCdaX+z8Y3IrYSp/HG+eIs1VBMW3wvLFFsfGgEvmaWONriBCfbMziwFDsEIT0oybtoR9dBskTV9DhO38YF77/67HHX6+o3s/c91BDX2G0kxLA1UWqAUZqVcm3Y+o/HK974C5ACBq0L3IFGdNUfMDei7cTl7GhLGvCoXKhD+8CjTn9Fbo1xnL7G0eEggALf/PSUf+3DQ2NsHBlhlpyZWtzQwDrVhXwm2WZAmXpftK4+GXg2I6NATMlR6zgO6K8RBcLk550z0fAMwqwckdOanHOQU8ZNUdw+PBtIJPdKvnEraYCwgBD1vLXQNPQaEC/4+HgDJiAOKQQx/dNSTBqlbEnr2+DplTZ7oiaWSSHfckicG6NKNj3EhqYW8pzPemh7dJwNHW+7pEMZfFKebOqm7mv0eOz572tjE1ZtPjC5Dn/ez8bXKSuorTbTMPgoQ63zR6YPp179e4Ls3bPaCe95GZjablb2BwQGnLHt7iCxmCQweAPAKCQgHwOorS0OWF/A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

