apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBL+BAdp/VdUzJD/cnhxPeZUd1VTpfnFjLzLAyf5nbTJDwQHv8uhisladocgmrrs24qg0B41624dxpSbHcGqSMjt/eVdHnH08rAMTkXC5/vAsEYRg3B+ee7xTTKHC7kOuN99aZGzzCglToVs6jwvUEtIxa6HTiDxTI88fyovsnSVp/97Oi5SXJQfq8OSu4RPgaZptWPfDRB0IGVNk9fnfqN6jrqKPNQkyIqkzxsmHlIjgjv1GDMK/g7a8pnwuV7ofbQ3RHMT1kbe8AybE4+9+LgUQLEfhSF4cUz2YhcUe/pSL9+3yaqamu0vaU/714fjYeC8kQO4+Fy215A0Y43zJOrdxmzXmCKcdt78f2e+O0MVY+rHdh22wM7JwRUXKMmFKahcRujYznA7hCybsEHwpXfVn14/0zcuTwa3XKmvgMBcQmNDDOWjr4DSFIynvxE3KkuhiMZocJRez2XTUom6qm4wSaLHQvDFBzczJpq6NANz80gaB8RmYbQDTHTXnn0Nm68v1xxaP4y/X7RfbLGDGhUnoL4cF+OS4BYIqqM2goWgmZdG0VD38XCU3MGzwZnMdXws9zAm4sKJVnMArUa4Liw40HrVngOTxjwsWeqasPqrMrsHlbjjhV251V5dmlD3Jf1RmMSuCro1le4PRxu+xIorR+TqaNUWKx+RFpGXaJ7Zu7vH6yW+DAUo0cmiFuNx/hdNAHiouKlrA0a6FinMEWsqLe9mMwf2TsSIz/1X0mi8Zbqr8DbpmtcxZn6mdDRF/chpoTD45bx96KS73XZLeuKep/byKlR3p8A0TR+rvMdV3qXGq77BoUchDrouXW7fusLpx3sSfsfFTLzF3kXOfZ/hZpJiXb7DAfIgdadgPs1/o7V47dcZ6ha4KrKjtuShB0S950=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

