apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgArhTB05jFi4nKJ8yPRgAeMl8iPASyT52Hislyi6Zz9wO2wOl2nsyH1frljkNgTJXnRMMwxXZKbVJa3uajMGzD6GzHCP2nT18fs67RMoRkuMgK4K3Eig6D61gS9QOxFfw/bXpBjlrIJdM9NkG6a9hWbW6EwYziuG26/m8c/DHn6XVPU3JOAxtzDVH+9ykosk7nRqnnKf+u4r9eHLEMc+WvhUbVVZp30KnoVv3vciDEQBzWeyYsU9CVZ6MUSyqkxr4S9GNn7UxP4sLBDtNDqZX+gu+dkmBYH/abWewAcxhI3qAnHxhqkxPoBaAhGWrWyvyZJHLXVyTFwMsGq/+dvJyhr+HqmgzOl8pGIjFmHVXjqa3PW1uGfrDfPbzdVJnvOS5vV4xet2+1IpdqSqjHesWdBCgGY0rdZ1sZCCaCemNTaF2brUVAX0x7KEAfuBysa0rAJnADN55H+z2uwUro9qnaB7SvOGdzGAmjgIVyaBxJn3pQ2XYNUV6qcWYT07SOshEEWY8U8yYvaIxEYrWxmQ7uQSWXoEr00Ogu9hweFXZ5bLNGQfVNq1wlwQbEsX9mnabjRNEm+Pu3oklESDNl8/gI2WoQtc/5dHZuP3hliBO1ey+iHsqm/NdET/ocGszvGxuPXwzu45o5/RqP+9VUWY1HhngOh1nYPjDPpCf9OqZusiW2vuWQpYTv0hFcDKcRq4mFHRBLUcu7IwyjADnBYW2MPA7dmunmII/5wZgebjhkhGnS1Y/IU4wJW+nFwDG/aQz8KhGxdL0YfIEMNHuo/ISV2SIvha36jht0rlR1X0CTRtPLAR4lyOu9VMhfN0VjqyW5fcleuJEmNwRWQb2CUp26QxR30oJYq4TzBwjPlfUmYg8ZVAqEUiCSW7a+RZovMxCvxVMnPzjpJ1Jf7dOZyy3OUEzP75CttNaG565NpMnhmtzO4J+Wy6d8r8BqtiPsKeTT/fOgyeb4QWIP0vyYP8ohZo7NBELWoE/RuY+pW8KoC4iKYZkUoaTGUf6GUosoDfMia6EjfBZmOQVVtnV0DSaI/i1c/tQNsD9YrlUub2b+mo3+yEZ7hobktsCrKXTXZSKLhmKkPRdxhyG6jDqJTUrANkbki3zlE9Qg/hDZhWPzjABiP7KD6vuu4r8pi0x2FrKIqoSjnWlUX3B3XkD6senZ7I5WWwKu78GIGdV/aah1L7EyTedzLXqNYfQVxeYh8hHt7rdLL2ra/w0dmsW76LBnJ2Cgms2MRoKLpvyUCg2Y7OilZjrKB+nZDBn3CbHPcSZeNk++g/KaVyIajKm87DF8CawspK2bcOYIwEuXMMvACOe+3fkqGRzzRYKLilIHempIcrk7o+a2c0+DFMZwOZNSlTYq4223ChycQVanPzrILE7JGpT8Y0risb3jbkchMC9kfXbwPpk3IgAGuHUpdnXPfMVReQ9eDbKRJoMcc9Ed3pxpnjm7LVRr78iKoL81cCb5DRqSTu82oJBnxvZk99QZEe3kYcZoTEeVVVhrcFZ8lLUyrCOsDsPXUaMROisDNXw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: azure-creds
      namespace: crossplane-system

