apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB9w4gIBmwAUMzAOZiXWOwKGb0WzTXqMUTFa+l+LdqEw2/knOhO/rMoPZRQro9uS3QTKOxBGWKXcw7O/tUTSqDzw2/o8qVNuuNy2nyYkfjCaw0MFfYr44yUqxHQMRVmiHrAlyI/yj46MgB710YEEbcqyucYk2KuDN2cA4L9cCVm0a2LRdaSt1Jb71JJWIPg07UMdoSGDmADr84uIup8krkhtQh7emdFwYrhwQEAlLe/CDHZxfxzOwj7kuzRiKsO/UPgFADAX50T45yBdnsk6MlZj9C4W/77ljCzj5MHxfatBJwwKlstrHwcrbZFtvYggAu04GB1L6zXzzn5IrF2yUDtXClIIGO0eNGYzsdtBsPjFC/cessYfv7PiAyV5s4lx310hVFPoStzZdJO8HD2HSJRvRS+DbCYAYPoS3S34SOSwCBxnASNeYXBhzy6b+tEkeb1uW1vMyy6tShWB/NThewjKadG5Y1yO/McCm48whIgm2qU1J+l7bl43p4NYSmnQskTxXplqooBvd7/1E0G7ZyxKF+yN1sQu9VxhUOlDqG3Z8jOlSyhMVvGKIJQxG/0BjBCql9y7vjDDw/NW19ks9yjUj3ydE5T9ynyiN//vvvbbQlCoBoBdZixI61P/dL84WAHs9awy0sgY/1R1YnTyaW2PluSDy711uyCbb64U4CCzIOk3w/cGgDXbOY6yzNQyVjPSEUU+6GoiKtFa4fu6DcrxF7lhuwWgVDZ1nZmlKSQph20WZnyAFQQyX/XC4UX1nDhIEJYv4fY/K90nhFuUyGUxzjwUA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-creds
      namespace: crossplane-system

