apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAU2MusRa76DzVjtjDwTFGsOlXzwhD+HdCIhuJ2J6QdUTRuv0Dd2HyKJ/zmHX5/ghTD2KfR3v1C18yVT9KYI0gC1MAam1Z2KSc+95ffbM64/Lc4D/rHdnXGKoOu9Ak0g28PWDU+RyRdt1UPe11zkVgepGGyL0yesz2FMbO79bPDc5hL1DqG28X4U5GQFLP+UAkD2fDM5chrrAHf817Dm83wGFhqpZbbIsvvqvDnmpANAUCCOQ6hUtyvw1ArrI+u+SqmDzGYcapHFsbyFspVAaYfGfupvvxwIQAT1Kixr5+Y3x1px0UF12h4m32ETLoEWmhE29XqmrhHSl8YgQH4xBoL2vOvYBVyGYNWTDnkVYQRJ7aj7VlhWwueAuz6zji7nIbLlUTOsLj51DrTdAlTzE2SrpyDq38lslaW4ePsnDn6LF8tfr3bvnv9aZqm3rsqMXAhgC1rUihTzO0hWCztZD4SK4M6t5oPKa7QY6bo65N0cier72szJ7/FsEmVZwuijdmM9Zncg4fMr4a9YJpOHlAnQrRlqqNs9Zl3QbOuJycYODgMu6kUdfGYN3LxqHhYNEGNxGpcNoHtxNkY2/bXchbzEsAJMYyNUxOPzydAh610ZjTTOZ+LqgIqUmrt1Mu9f2wJ7dgr7t9jK/qNtAxgvfC/g5J351ODRBAr3R+hXaN5t/Qa9nXzPZrBsay/+eMcNNElZ0iUdvyAj76zGE1aE8Nx0komdXEjAjGnfdA84/f8zeWcv4NRdTjnDwAWCI94d3zcAR6jkrtciEnL0T7L8/aophMwSols73uCo5nZ/nw5KFj3AHkIs+HqK0Vk5fkRxaGYatqPfMqKfcX33gY94XwqWQgyW9cVIYUR89DDOolxkFERLc+gLPOb+/sqm9ieW64PMtA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

