apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps-reqs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-app-reqs
    repoURL: https://github.com/vfarcic/crossplane-kubevela-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://9679D6DAC46D68EDFE5978E0B8E45D5E.gr7.us-east-1.eks.amazonaws.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
