apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-a-apps
    repoURL: https://github.com/vfarcic/crossplane-kubevela-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://DB0DB32E600068CCE7DAC801F332985D.yl4.us-east-1.eks.amazonaws.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

