apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo/argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    helm:
      values:
        server:
          ingress:
            enabled: true
            hosts:
              acme.com
          extraArgs:
            - --insecure
        controller:
          args:
            appResyncPeriod: 30
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
