apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a
  labels:
    cluster-owner: vfarcic
spec:
  id: team-a
  resourceRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: CompositeCluster
    name: team-aaa
  # compositionRef:
  #   name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    # minNodeCount: 1
