apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBL3dHO4fnw/URivJqFj3jNMppdTZkzwwT0gdjJ3heMq2i+bXgP0MWiN+s5nOPFjku4Lngi57g8j/I9MZRYUMQV5/lEjPflLypw5kzMyeokw4kQb0jY3zlT9imK/Z0NCG3WojoPu1tB0tftEtoro16F4XQUwlYBiNubcTPCLAFEf7Agvoa12uPX9tVfryIbUosL6Ilc3fJQzPHN0PaJxPK7CtrphRu9kYQ6LRECSYXSP4NC2wCXRo7E/OAn1vkoCX/sqFE8rT+kEzgPI0gwolvTNugLGzAvqpvMHV5f1sRPN+WkDwgrWJ+NYvwJGIq9A6TL4vc7I7ncu9ArtYztl667PDL1HV+Owgt4UUawODWnpDbfjLEhvMCEJSU9+wNfb8loj3jntj456gzceZ63KiY9E5fVxFI8bHC88Kb7hv7F4zy9eGE9Ho75P3ZSgl+8l/CwWiFP0GM4SvM+zuHE7xX2UegD5T5e1IKurt9C3nBTx8wcGtmy22r2Ltp/IGztPQ2qxqkwAC5DOwob28u1NBox+ha7JybsOJ5VPVrbHjQ34DgjwCxMBs/LQ3swHgcDkUnVFFKAkKeoMhVRcOck1yDQd+hlBp4UClmdXvzv1Vn2Ps7saCk4uMG/1EYcKQpBzdMd9uNMO3GZukgO6l8ThXCfBnB7sELtxJGPClU4wsa19/PZxXE1UxK1roI+fC+t7dU6sA3UqRRQzEoYjBYLyYe9ElSvML7LND/EIOwdGmwPRmM/qiFsSUiivBfbRb6Vtwij1n4GsJRqCWEDIbuPIlEjwp5wOb7Jyr9+dCK6xvpdD6tC1WD671p4975i9Sr7kWIsI2/LLEKQa6kpEsptBk0B03KC8XBWuQVSrzFXJhS3lQ61CoBWg2pprpGPZqnMxQfRrDA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

