apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBXBUoKxQnkih6IsIGWcQk7cpXocywhkOSKNMGciEfG3OxZ98UBOwbzSMXpAx5BsY0gxWOAwo1Gh91kDJ2pOUlZwWmskq9N1Wb4MU1xvEWWSB0TZVEQunSXKxPJ3EdkOY5T095QRmKm40kiYm0+NMqMlfE3mMqwALcM8BJ23DcQPyDFG3Gh7zxsWOYgW94kNQDA/ShpvWLbmfs6ywqGsnVZ1Y8aS3+Rg+wBUwmbLqPmf2ENsiPnPjDiyWZ6SHDc9vwuEx4nSKhasiWinBkT1XyumfApebO3Y4MG+T39qCtTHlIUzz8Gj6XPQcyohnvuKDJ9Gsky6ALla2CXU0Xefwy/U6/N460ICpaaP0mhuCcxf/9w6MuZcWpmmSxj9A/GA7x74CwA94lSJBSFiMZw9h3y0oAS3sJL4IbcfwlA/3gOqxn4a3G5xDARnIv+OL5ANKIYAkZ5p0p9jMnJYyCc/o/+yjCyuUPPN1Um4ZqAWxZibjCtrEYHNw6JWJYwH4N/sx+bGzwyp+QfJJ+4h+gvT2b5Jls8UVQfmcsNzK4zfLKLCTwWPDTf/Sqcdk2/nnGVM/IZ/kV5UPKOz8ByuW9q2ZR/9LKC8f3uezi1Eqm0CWL1RwRSi/EZPGruSRn0HritE6oYy+lOUO+J6r6S/8cxjdwinRza22+FFo7AThm4dA9a1ksB3c5wXshop7xWqnpXxWQ32M+kA8a6Rnl4S2lUqQUaKWiF26KXn6aiw7zHrtQh7Xhmf9dtFrXOCjTQi2wLRx579PnqgZJERoqLTDTMiBuBF5iUGH8kkAKkPYlEZk4vR5YAytoOn/p4PmwaMomT5xYnTSQP9KXnJ6CxGL/qP97ZKlww++Z5Ofai4G35/wxDTvGtKYjkDtBv7zNV8ioUwoSJqPs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

